services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    ports:
      - "8100:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      - redis
